name: admob_playground
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gallery_assets: ^1.0.2
  go_router: ^14.1.4
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_gallery_assets/crane/destinations/fly_0.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_1.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_2.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_3.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_4.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_5.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_6.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_7.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_8.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_9.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_10.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_11.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_12.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_13.jpg
